services:
  ms1_service:
    build:
      context: ./cloud-computing-project-ms-1
      dockerfile: Dockerfile
    image: dynast4/cloud-computing-project-ms-1:latest
    container_name: ms1
    ports:
      - "5001:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - MS2_ACCOUNTS_URL=${MS2_ACCOUNTS_URL}
      - MS4_COMPLIANCE_URL=${MS4_COMPLIANCE_URL}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
    depends_on:
      - mongodb
    networks:
      - ms1
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - ms1
      - loadBalanced

  mongodb:
    image: mongo:7-jammy
    container_name: ms1-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=customer_service_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ms1
    restart: unless-stopped

  ms2:
    build:
      context: ./cloud-computing-project-ms-2
      dockerfile: Dockerfile
    image: warleon/cloud-computing-project-ms-2:latest
    container_name: ms2
    ports:
      - "5002:3000"
    profiles:
      - loadBalanced
      - ms2

  ms3:
    build:
      context: ./cloud-computing-project-ms-3
      dockerfile: Dockerfile
    image: warleon/cloud-computing-project-ms-3:latest
    container_name: ms3
    ports:
      - "5003:3000"
    profiles:
      - loadBalanced
      - ms3

  ms4:
    build:
      context: ./cloud-computing-project-ms-4
      dockerfile: Dockerfile
    image: warleon/cloud-computing-project-ms-4:latest
    environment:
      DB_PASSWORD: ${MS4_DB_ROOT_PASSWORD}
      DB_NAME: ${MS4_DB_ROOT_DB}
      DB_USER: root
      DB_PORT: 3306
      DB_HOST: ${MS4_DB_HOST:-mysql}
      FRAUD_API_URL: ${MS4_PUBLIC_URL:-ms4}
      GIN_MODE: release
    container_name: ms4
    ports:
      - "5004:8080"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    profiles:
      - loadBalanced
      - ms4
    networks:
      - ms4
    depends_on:
      mysql:
        condition: service_healthy

  ms5:
    build:
      context: ./cloud-computing-project-ms-5
      dockerfile: Dockerfile
    image: warleon/cloud-computing-project-ms-5:latest
    container_name: ms5
    ports:
      - "5005:3000"
    profiles:
      - ms5
      - ingest

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MS4_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MS4_DB_ROOT_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    profiles:
      - ms4
      - ms4-dev
      - database
    networks:
      - ms4
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:
  mongodb_data:
    driver: local

networks:
  ms4:
    driver: bridge
  ms1:
    driver: bridge
